apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-registration-webhook-hosted
  namespace: {{ .ClusterManagerNamespace }}
spec:
  type: NodePort
  selector:
    app: {{ .ClusterManagerName }}-registration-webhook
  ports:
  - port: 8081
    targetPort: 6443