apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:{{ .ClusterManagerName }}-registration:webhook-user
rules:
# Allow user to create admission review
- apiGroups: ["admission.cluster.open-cluster-management.io"]
  resources: ["managedclustervalidators", "managedclustersetbindingvalidators", "managedclustermutators"]
  verbs: ["create"]
