apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.admission.work.open-cluster-management.io
spec:
  group: admission.work.open-cluster-management.io
  version: v1
  service:
    name: cluster-manager-work-webhook
    namespace: {{ .ClusterManagerName }}-open-cluster-management-hub
  caBundle: {{ .WorkAPIServiceCABundle }}
  groupPriorityMinimum: 10000
  versionPriority: 20
