apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: managedclustermutators.admission.cluster.open-cluster-management.io
webhooks:
- name: managedclustermutators.admission.cluster.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    caBundle: {{ .RegistrationAPIServiceCABundle }}
    service:
      # reach the webhook via the registered aggregated API
      namespace: open-cluster-management-hub
      name: cluster-manager-registration-webhook
      path: /apis/admission.cluster.open-cluster-management.io/v1/managedclustermutators
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - cluster.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - managedclusters
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 3
