apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-registration-webhook
  namespace: {{ .ClusterManagerName }}-open-cluster-management-hub
spec:
  selector:
    app: {{ .ClusterManagerName }}-registration-webhook
  ports:
  - port: 443
    targetPort: 6443
