apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-work-webhook
  namespace: {{ .ClusterManagerNamespace }}
spec:
  selector:
    app: {{ .ClusterManagerName }}-work-webhook
  ports:
  - port: 443
    targetPort: 6443
