apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .ClusterManagerName }}-work-webhook
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    app: {{ .ClusterManagerName }}-work-webhook
spec:
  replicas: {{ .Replica }}
  selector:
    matchLabels:
      app: {{ .ClusterManagerName }}-work-webhook
  template:
    metadata:
      labels:
        app: {{ .ClusterManagerName }}-work-webhook
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .ClusterManagerName }}-work-webhook
          - weight: 30
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .ClusterManagerName }}-work-webhook
      {{ if not .DetachedMode }}
      serviceAccountName: {{ .ClusterManagerName }}-work-webhook-sa
      {{ end }}
      containers:
      - name: {{ .ClusterManagerName }}-work-webhook-sa
        image: {{ .WorkImage }}
        args:
          - "/work"
          - "webhook"
          - "--secure-port=6443"
          - "--tls-cert-file=/serving-cert/tls.crt"
          - "--tls-private-key-file=/serving-cert/tls.key"
          {{ if .DetachedMode }}
          - "--kubeconfig=/var/run/secrets/hub/kubeconfig"
          - "--authentication-kubeconfig=/var/run/secrets/hub/kubeconfig"
          - "--authorization-kubeconfig=/var/run/secrets/hub/kubeconfig"
          {{ end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: webhook-secret
          mountPath: "/serving-cert"
          readOnly: true
        {{ if .DetachedMode }}
        - mountPath: /var/run/secrets/hub
          name: kubeconfig
          readOnly: true
        {{ end }}
      volumes:
      - name: webhook-secret
        secret:
          secretName: work-webhook-serving-cert
      {{ if .DetachedMode }}
      - name: kubeconfig
        secret:
          secretName: {{ .ClusterManagerName }}-work-webhook-sa-kubeconfig
      {{ end }}

