apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-work-webhook
  namespace: {{ .ClusterManagerNamespace }}
spec:
  selector:
    app: {{ .ClusterManagerName }}-work-webhook
  ports:
  - name: webhook-server
    port: 443
    targetPort: 6443
  - name: webhook
    port: 9443
    targetPort: 9443
