apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.admission.cluster.open-cluster-management.io
spec:
  group: admission.cluster.open-cluster-management.io
  version: v1
  service:
    name: cluster-manager-registration-webhook
    namespace: {{ .ClusterManagerNamespace }}
    {{if eq .RegistrationWebhook.Port 0}}
    port: 443 
    {{else}}
    port: {{.RegistrationWebhook.Port}}
    {{end}}
  caBundle: {{ .RegistrationAPIServiceCABundle }}
  groupPriorityMinimum: 10000
  versionPriority: 20
